### ISSUE TITLE
Add command to ping services / Pi's

### ISSUE THREAD

**Issue by eamonburns** [btc-raspberrypiclub/piclub-bot#2]
This should take security into account. Using `os.system(f"ping -c 1 {service}")` to ping a service would be insecure (e.g. someone could make `service` be `google; sudo rm -rf /`)

In this case, I think `subprocess.run(["ping", "-c", "1", service])` would be more secure

**Comment by eamonburns** [comment]
Related to #1, and #6, because it might be a good idea to make a command that creates new services to ping, and only "bot moderators" should be able to use it

**Comment by eamonburns** [comment]
There also could be a `healthcheck` option. Which pings all services, and gives a report

**Comment by eamonburns** [comment]
Or, instead of a `healthcheck` command, there could be a `/ping group` command which pings all services that are part of a group, and each service has an optional list of groups that it is part of (all services are part of the `all` group). For instance:
```yaml
# config.yaml

# ...

services:
  google:
    address: google.com
    groups:
      - external
  pi1:
    address: 192.168.0.201
    groups:
      - internal
      - pi-cluster  
  pi1:
    address: 192.168.0.202
    groups:
      - internal
      - pi-cluster
  vm-server:
    address: 192.168.0.200
    groups:
      - internal
```
---
```
/ping group external

pinging services: google
```
```
/ping group internal

pinging services: pi1, pi2, vm-server
```
```
/ping group pi-cluster

pinging services: pi1, pi2
```
